### PR TITLE
best practices 2

### PR DESCRIPTION
**Pull request by kasperpeulen**
added a grinder script to run more easily do dart format for the whole package

added .analysis_options to ensure dart style conventions

### CODE REVIEW

**Comment by kasperpeulen** [comment]
the dart style guide says now to not use screaming caps for constant identifiers:
https://www.dartlang.org/effective-dart/style/#prefer-using-lowercamelcase-for-constant-names

not sure what you're opinion is about that, so I uncommented that rule for now

**Comment by kasperpeulen** [comment]
oh, and I also run `loadExampleData()`, because that makes the demo much more interesting I thought

**Comment by kasperpeulen** [comment]
one other convention I believe is to make field in the components that are not used in the view private, @jwashin what do you think about that?

**Comment by jwashin** [comment]
I think, for a demo, private fields might be overkill, but if it helps keep things orderly in the long run, for example in a big app with multiple authors, maybe it would be good discipline to show.

**Comment by kasperpeulen** [comment]
okay @jwashin I will do that then as well, I think another advantage is that it kind of shows what will be used in the view, and what only is used internally in the controller itself

there is this other style guide, that some people don't like, so therefore I ask it, that is to use inference for local variables, for example:
`String a = aString.substring(0, 3);`

can be inferred, so then the style guide says to use:
`var a = aString.substring(0, 3);`

**Comment by jwashin** [comment]
These look good. I'll go ahead and merge.

**Pull request merged**
